datasource:
  maximum-pool-size: 20
  minimum-idle: 10
  url: jdbc:oracle:thin:@(DESCRIPTION=(CONNECT_TIMEOUT=5)(TRANSPORT_CONNECT_TIMEOUT=3)(RETRY_COUNT=3)(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=172.20.1.209)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=emedprd_prd.subnetprdprivat.vcnemed.oraclevcn.com)))
  
spring:
  datasource.hikari:
    maximum-pool-size: ${datasource.maximum-pool-size}
    minimum-idle: ${datasource.minimum-idle}

eureka:
  host: eureka-server
  port: 8761
  name: eureka
  client:
    registry-fetch-interval-seconds: 10
    renewal-interval-in-seconds: 30
    instance-info-replication-interval-seconds: 10
    serviceUrl:
      defaultZone: http://${eureka.host}:${eureka.port}/${eureka.name}
    healthcheck:
      enabled: true
  instance:
    ipAddress: ${HOST_IP}

app:
  storage:
    baseUrl: '${GATEWAY_BASE_URL:https://gateway4all.emedbr.com}/storage'
    baseDir: /app/storage
    type: filesystem
    uploadDir: upload
    useSignedUrl: true
    maxFileSizeBytes: 41943040
    maxImageSizeBytes: 4097152

kafka:
  hosts: 172.20.1.149:9094

mongodb:
  host: 172.20.1.212
  port: 27017
  username: admin
  password: MongodbEmedbr4All
  
redis:
  host: 172.20.1.150
  port: 6379
  
