# Default pool size DEV
spring.datasource.hikari:
  maximum-pool-size: 5
  minimum-idle: 1

app:
  storage:
    baseUrl: '${GATEWAY_BASE_URL:https://emed-gateway.univision.net.br:8443}/storage'
    type: filesystem
    baseDir: /app/uploads
    uploadDir: upload
    useSignedUrl: true
    maxFileSizeBytes: 41943040
    maxImageSizeBytes: 2097152
