server:
  max-http-header-size: 32768
datasource:
  maximum-pool-size: 2
  minimum-idle: 1

spring:
  jackson:
    jserialization.write-dates-as-timestamps: false
    date-format: "yyyy-MM-dd'T'HH:mm:ssZ"
  datasource:
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM DUAL
  hikari:
    maximum-pool-size: ${datasource.maximum-pool-size}
    minimum-idle: ${datasource.minimum-idle}
  data:
    mongodb:
      maximum-pool-size: 10
      uri: 'mongodb://root:Un1m3dM0b!l3@104.198.166.118/emed-bus?authSource=admin&authMechanism=SCRAM-SHA-1'
  kafka:
    listener:
      ack-mode: record
      concurrency: 6
    consumer:
      properties:
        request.timeout.ms: 30000
        retries: 8
        retry.backoff.ms: 5000
        fetch:
          min:
            bytes: 30000
          max:
            wait:
              ms: 500
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval-ms: 5000

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 0

eureka:
  host: localhost
  port: 8761
  name: eureka
  client:
    serviceUrl:
      defaultZone: 'http://${eureka.host}:${eureka.port}/${eureka.name}/'
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true



swagger:
  title: 'Emed 4ALL'
  version: '@project.version@'
  termsOfServiceUrl: 'https://www.apache.org/licenses/LICENSE-2.0'
  contact:
    name: 'EmedBr'
    url: ''
    email: ''
  license: 'Apache License 2.0'
  licenseUrl: 'https://www.apache.org/licenses/LICENSE-2.0'

management:
  endpoints:
    web:
      exposure.include: '*'
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
    refresh.enabled: true
  metrics:
    export:
      prometheus.enabled: true
  health:
    show-details: ALWAYS
  security.enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 100000
        timeout.enabled: false
  threadpool.default:
    coreSize: 70

app:
  storage:
    baseUrl: '${GATEWAY_BASE_URL:https://emed-gateway.univision.net.br:8443}/storage'
    baseDir: /app/storage
    type: filesystem
    uploadDir: upload
    useSignedUrl: true
    maxFileSizeBytes: 41943040
    maxImageSizeBytes: 2097152
  google:
    projectId: ucwbmobile-test-182416
    storage:
      bucketName: '${STORAGE_BUCKET_NAME:emed4all-dev}'
      key: >-
        ${STORAGE_KEY:ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAidWN3Ym1vYmlsZS10ZXN0LTE4MjQxNiIsCiAgInByaXZhdGVfa2V5X2lkIjogIjNiZGE1ZTAxNzE2NjEwODRmYzkwY2QyOWRlMzIzMjkzZTA0ZGE2NmIiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRREJDbmJuUjdsa0M1T0lcblRyZnBkSENaY2RzRDN1ZU8vYUFHUzNKMEtyRnRpaXU3Qm9wSis4SisyWHJxZlNhTGh6RjEzQVBVWWM1SFB6UFdcbkFQbEsxNnJOdWorV3hmSnM2Mlh5MUhPejRtVzNXeThIZGtBTmMyMSt2a2xLeWNILzZWaXdwcjlPa3R4dHpEajZcbldwcmttRjZPRGl5R1FHU3VVTTY0czNFRGdtQXQ4bjZ2V0NMSkt2OVhBQjRQRmNsSkl2d1JTOVd2QlRGV0hNc3JcbkJqWnBjVjVLREFKdFQvVXBaS1ZPcXdTbnVpclh3ZHBOaHBGSm0vQXNuV1Z1TTZ3Z3o0OVRibENCL2ZtUEt3UjFcbnJZa2EyWEVRWFJuZ2MxdmdXalBXSlZNYk5rSTJTQkZCSDFabTZ6OTk2clVjRjhUSlVCM3dxVjg1R0lTT3Fmd2lcblRDdWpZSEtGQWdNQkFBRUNnZ0VBVG5qRGh4YjMvUHhidDlCUUlMMnR2Q0sxWm1ocGR3NFF6QjVGWTRXclpKMERcblU5Ni92bjF5UGdDSVgrUUtGRFFiM2c1WEhERzZHZXBPVnhORVE3RlNCSmxPbWlyVGRvVm1od1RvRjlyVGdHcTNcbnZtL0tiKzFaT0dsLy83L3VkZXBVbkZMY2Q4TnBpZFMzNE1XT0s1am83eFJCOHowZjhHQjIrRXd4aDd5cS9tSGRcbk9oWmVHZmc3ZWxHSWNtQ2ljRzQybWdTZjJoZ0JPcGxuWHovOHVkK05MVFE2QmlmM0gzMDlOTVl6ZFFEYm1yMWlcblBuRnpoQ29keUt5UEFxT2toTnNabG84cnVpNGNqMnY4QlhlYldPYUlSYXRqT3BRV3E4Zlh6MEtzc0FKdCt2amhcbnQ2RFpFVERBUkFQY0VkYTNicHNrV3lRUVRyVVNWNXI1RGpBZkhzMzJiUUtCZ1FEcG93b2I2Y0NLVUxGajZhQ0pcbjRLZUJWd0xVOVBJRXZLMHdadm0xNUxPWHNBcVJzUTdKMy9oeTVpd0EyU3pCeWpIaUVIcEpabzZReTI0dkNERXhcbjZLc1NFWjhsaitHb2JVSFN0TEk2Yk1nOGVybmRKV1Q3S2tYUlA2US9mK3BnUit4SHVnSzRSdEVLdVEvMkVLYlpcbkFTMlFKMGhzS3ZEUnE1dEdHVGQzdWp4NVZ3S0JnUURUaEt5VWZaY3FKMWdSei9hM0FSU2ZKM1FqMTMxODQzQzRcbk1WSmZBTGVZdUVMakE3V0Q0NnExUDJKRmVYZ1U0N0hyV0RKd2hMMnhkRWpKSmlaaXVzRk8xb3NrSVNGVjM5S29cbkNoSzhpYUZOMWUrMzNTcDdnTXFaZ1BjWkR1QVdDY1pxRitydzEyai9ZZGxqK3hHcGRLVHhMcGJCeFl0QUI5dWNcbnd2aFh5WnlkZ3dLQmdCUHJ4dXppWFh4dHJQSnI5VGhNWTN2dncxb05HS1cyd0wyanloN3NSVFBsMnNEWmEvMWlcbmozaWNqNXZ5NkpJTmYzdGJGRkkxNEdvUUxuRHNMZVduaFE2aFdnU0Y1Q1BNVFJSK084UW5pbHM5eTZORGtQeXBcbmVoS0JicXZMYUZ5VlJWeElTL3NTYnJpUFZ3RVFJbW5XWStBcXVVNGZ5ekRWaFFQUkdwMm16NGs1QW9HQUFiQWVcblhIVUFIdEwvamV6VjhESHZBeklpYUNMUkdvMEtHajR5aFJXUllZT2U3UWJialBqbEpOc2pvcUJNaUFZbEpsYW1cbjJHVUd5b0srRGZUaSs0aTRBRFFRR2pLMWZHVHozbWx1S3RrQ1U0ZXdpUXdYeWJLR2EyRXZGNkVad3JORFJSZDVcbnhZQkNrejhwcC9XWjkzczUwYjdvYnhWdmZneFNBVmRBK2hwZXlKY0NnWUVBakZJLzhLeWtQSS9DT09xMWRzZ0xcbnJBOHhOcW1SY1VFU25JblBVQlRaeDA2b0VRRHhmbXk0emJ6bzkyemVxNjVZOTFvUG9DNzdLeHpYNmZjOWl5UmRcbnRKbGNaZG42YnBMeFJGckV0R25MaFdmU0J0VEdJRFZ5TGRLNVZkdjJPcnJsRUhjdWhrR0ttZG9VSXB2dzdsSldcbi8yZFFDWEtjcWJUNS92N1RXS2dVSHdjPVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImVtZWQtc3RvcmFnZS11cGxvYWQtYWRtaW4tZGV2QHVjd2Jtb2JpbGUtdGVzdC0xODI0MTYuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTAyMDM5NDI3NDQ4MDE5ODkzNTI1IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9lbWVkLXN0b3JhZ2UtdXBsb2FkLWFkbWluLWRldiU0MHVjd2Jtb2JpbGUtdGVzdC0xODI0MTYuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0K}
