datasource:
  maximum-pool-size: 10
  minimum-idle: 3
  url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.20.3.51)(PORT = 1521))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME =pdb_emedhml.subnethmlprivat.vcnemed.oraclevcn.com)))

spring:
  datasource.hikari:
    maximum-pool-size: ${datasource.maximum-pool-size}
    minimum-idle: ${datasource.minimum-idle}

eureka:
  host: eureka-server
  port: 8761
  name: eureka
  client:
    serviceUrl:
      defaultZone: http://${eureka.host}:${eureka.port}/${eureka.name}
    healthcheck:
      enabled: true

app:
  storage:
    baseUrl: '${GATEWAY_BASE_URL:https://emed-gateway-hml.univision.net.br:8443}/storage'
    baseDir: /app/storage
    type: filesystem
    uploadDir: upload
    useSignedUrl: true
    maxFileSizeBytes: 41943040
    maxImageSizeBytes: 2097152

kafka:
  #hosts: PLAINTEXT://164.152.70.221.128:9094,PLAINTEXT://146.235.57.4:9094,PLAINTEXT://150.230.70.178:9094,PLAINTEXT://144.22.253.92:9094
  hosts: PLAINTEXT://kafka:9092

mongodb:
  host: mongodb
  port: 27017
  username: mongodb
  password: 25ymtkBpc4tf2wNHeTpW

redis:
  host: redis
  port: 6379
  #password: is5q7cChvw
