spring:
    cloud:           
        gcp:
            credentials:
                location: classpath:service-account.json
            project-id: ucwbmobile-test-182416

server:
    port: ${PORT:${SERVER_PORT:9002}}
    undertow: 
        ioThreads: 15
        workerThreads: 300
 
swagger:
    title: Beneficiário
    description: Microserviço das APIs de Beneficiário

notificacao:
    utilizacao:
        titulo: Notificação Uso do plano
        texto: Caro beneficiário, informo que identificamos a utilização do plano de saúde
    informacaoIntercambio:
        titulo: Informações Intercambio
        texto: Caro beneficiário, você está fora da área de atuação da sua Unimed.
        
sosUnimed:
    path:
        storage: /opt/apps/storage/upload/sos-unimed
        url: https://gateway-test.appunimed.com:8443/beneficiario

url:
    correios.cep: http://viacep.com.br/ws/
    portal-unimed:
        consulta-token: https://api-preproducao.portalunimed.com.br/tokens/v1/consultatoken/{key}

res:
    textoCadastro: Autorizar acesso ao RES
    textoAlteracao: Modificar acesso ao RES
    botaoCadastro: Acesso ao RES
    botaoAlteracao: Modificar acesso ao RES
    # UVNSSO-582 Token Cartão Virtual Portal Unimed Brasil
    url:
        consulta-token: https://api-preproducao.portalunimed.com.br/tokens/v1/consultatoken/{key}
    bearer-token: Basic cG9ydGFsdW5pbWVkOnBvcnRhbDAwMQ==   




cartao:
    token:
        # considera se geracao via totp nao estiver ativo
        minutos_expiracao: 2
        totp:
            ativo: true
            chave: secret
            expiracaoSegundos: 1800
            posicoes: 10
        
    # TODO retirar apos implantacao Cartao Virtual
    cache:
        # Tempo de Expiração do cartão em dias
        expiracao: 1 
    familia:
        atualizar: false

informacaoIntercambio:
    diasReenvioPush: 30

google.maps.api.key: AIzaSyC7rWADxHtoFLlYmgI8tvpoXJaLZRDvlHE

field:
    beneficiarioDto:
        codigo: Código
        cpf: CPF
        estado: Estado
        enderecos.telefone: Telefone
        enderecos.celular: Celular

protocolo:
    dias: 180
    
beneficiario:
    regras:
        regraTotalDiasParaRetorno: 10
    schedule:
        especialidade:
            fixed-delay: 86400000  
    # TODO retirar apos implantacao Cartao Virtual
    cache:
        # Tempo de Expiração em dias
        expiracao: 1
    integracao:
        excluirInativo: false

storage:
    bucket: 
        name: unimedmobile-test
        path: upload/protocolo-ouvidoria/
    path:
        service-account: service-account.json
    project-id: ucwbmobile-test-182416
    
unimedBrasil:
    geracaoToken:
        urlAccesToken: https://gateway-hml.unimed.coop.br/oauth/v1/access-token
        urlSolicitarToken: https://gateway-hml.unimed.coop.br/cartao-virtual/v1/tokens
        clientId: d4f83eef-9634-443a-af9e-8a7edd9d37e9
        clientSecret: 54000380-0d27-49df-afe8-62beb3e46d9d