spring:
    cloud:           
        gcp:
            credentials:
                location: classpath:service-account-dev.json
            project-id: ucwbmobile-test-182416

beneficiario:
    schedule:
        especialidade:
            fixed-delay: 86400000
    regras:
        regraTotalDiasParaRetorno: 30
        
storage:
    bucket: 
        name: unimedmobile-test
        path: upload/protocolo-ouvidoria/
    path:
        service-account: service-account-dev.json
    project-id: ucwbmobile-test-182416        

unimedBrasil:
    geracaoToken:
        urlAccesToken: https://gateway-hml.unimed.coop.br/oauth/v1/access-token
        urlSolicitarToken: https://gateway-hml.unimed.coop.br/cartao-virtual/v1/tokens
        clientId: d4f83eef-9634-443a-af9e-8a7edd9d37e9
        clientSecret: 54000380-0d27-49df-afe8-62beb3e46d9d