server:
    port: ${PORT:${SERVER_PORT:9034}}

swagger:
    title: CSPar Service
    description: Microserviço de integrações com a CSPar
    contact:
        name: Univision
        url: ""
        email: ""

spring:
    jackson:
        serialization:
            write-dates-as-timestamps: false
        date-format: yyyy-MM-dd'T'HH:mm:ssZ
    data:
        mongodb:
            database: cspar-dev

