spring:
  datasource:
    url: jdbc:oracle:thin:@(description=(address=(protocol=tcp)(host=172.20.1.209)(port=1521))(connect_data=(SERVER =DEDICATED)(service_name=emedprd_prd.subnetprdprivat.vcnemed.oraclevcn.com)))   
    password: 'EMdadm@!'
  kafka:
    bootstrap-servers: ${kafka.hosts}
  redis:
    host: ${redis.host}
    port: ${redis.port}
    #password: ${redis.password}
    repositories:
      enable: true