spring:
  datasource:
    url: ${datasource.url}
    username: EMEDAGD_QA
    password: '3m3dAgd44ll01$#Med'
  mongodb:
    maximum-pool-size: 10
    uri: mongodb://${mongodb.username}:${mongodb.password}@${mongodb.host}/qa?authSource=admin&authMechanism=SCRAM-SHA-1
  kafka:
    bootstrap-servers: ${kafka.hosts}

app:
    site.url: 'https://app-qa.emedbr.com'