spring:
  datasource.hikari:
    maximum-pool-size: 5
    minimum-idle: 1
  mongodb:
    maximum-pool-size: 10
    uri: mongodb://${mongodb.username}:${mongodb.password}@${mongodb.host}:${mongodb.port}/qa?authSource=admin&authMechanism=SCRAM-SHA-1
  application:
    name: emed-administrativo-server
  datasource:
    url: ${datasource.url}
    username: EMEDADM_QA
    password: '3m3dAdm44ll01$#Med'
  kafka:
    bootstrap-servers: ${kafka.hosts}

app:
  site:
    portal: https://app-qa.emedbr.com/portal
    url: 'https://app-qa.emedbr.com'
  cadastro-usuario:
    log-senha-gerada: true
  site.url: 'https://app-qa.emedbr.com'
  id-usuario-master: 40520

