spring:
  datasource:
    url: jdbc:oracle:thin:@10.10.15.58/XE
  #Kafka properties
  kafka:
    bootstrap-servers: PLAINTEXT://kafka-2-vm.c.ucwbmobile-test-182416.internal:9092

#Parâmetros específicos do serviço
app:
  site.url: 'https://emed.univision.net.br'
