server:
  port: 9004

spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.username}:${mongodb.password}@${mongodb.host}/prod?authSource=admin&authMechanism=SCRAM-SHA-1
  datasource:
    maximum-pool-size: ${datasource.maximum-pool-size}
    minimum-idle: ${datasource.minimum-idle}
    url: ${datasource.url}
    password: 'EMdpep@!'
  #Kafka properties
  kafka:
    bootstrap-servers: ${kafka.hosts}
app:
  id-usuario-master: 40520
    

criptocubo:
  url: https://api.cryptocubo.com.br/api/eletronic-signatures/v0/
  params:
    operation: sign
    type: qualified
    format: cms
    profile: adrb
    icpbr: false

  header:
    key: 93e7e4ffc3ea4b16bf23ff824a886826
    trace: true

  body:
    format: attached