spring:
  datasource:
    url: jdbc:oracle:thin:@(description=(address=(protocol=tcp)(host=172.20.1.209)(port=1521))(connect_data=(SERVER =DEDICATED)(service_name=emedprd_prd.subnetprdprivat.vcnemed.oraclevcn.com)))
    password: 'EMdadm@!'
    hikari:
      maximum-pool-size: ${datasource.maximum-pool-size}
      minimum-idle: ${datasource.minimum-idle}
  data:
    mongodb:
      maximum-pool-size: 10
      uri: 'mongodb://root:Un1m3dM0b!l3@104.198.166.118/emed-bus?authSource=admin&authMechanism=SCRAM-SHA-1'

mongodb:
  host: 129.148.58.122
  port: 27017
  username: root
  password: X3GAOK2jVc