spring:
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.20.3.51)(PORT = 1521))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME =pdb_emedhml.subnethmlprivat.vcnemed.oraclevcn.com)))
    password: '3m3dRep44ll01$#Med8'
    hikari:
      maximum-pool-size: ${datasource.maximum-pool-size}
      minimum-idle: ${datasource.minimum-idle}

  kafka:
    bootstrap-servers: PLAINTEXT://localhost:9092