spring:
  datasource:
    hikari:
      maximum-pool-size: ${datasource.maximum-pool-size}
      minimum-idle: ${datasource.minimum-idle}
    url: jdbc:oracle:thin:@(description=(address=(protocol=tcp)(host=172.20.1.209)(port=1521))(connect_data=(SERVER =DEDICATED)(service_name=emedprd_prd.subnetprdprivat.vcnemed.oraclevcn.com)))
    password: 'EMdagd@!'    
  data:
    mongodb:
      uri: mongodb://${mongodb.username}:${mongodb.password}@${mongodb.host}/prod?authSource=admin&authMechanism=SCRAM-SHA-1
  kafka:
    bootstrap-servers: ${kafka.hosts}

app:
  site.url: "https://emed-hml.univision.net.br"
