spring:
  datasource:
    url: ${datasource.url}
    password: '3m3dAdm44ll01$#Med8'
  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 2587
    username: AKIAVQV3IQRIVJLCYRNK
    password: BDCAWS3vMLmRjMoHAba1szirfjlJdG7X/huaX6bwkV+t
    properties:
      mail:
        smtp:
          from: mobile-dev@appunimed.com
      personal: Emed Hom
  kafka:
    bootstrap-servers: ${kafka.hosts}
management:
  endpoints:
    web:
      exposure.include: '*'
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
    refresh.enabled: true
  metrics:
    export:
      prometheus.enabled: true
  health:
    show-details: ALWAYS
