server:
  port: 9010
spring:
  application:
    name: emed-websocket
  redis:
    uri: redis://localhost:6379
    repositories:
      enable: true

logging:
  level:
    org:
      hibernate:
        type: debug
