server:
    port: ${PORT:${SERVER_PORT:8099}}
    
security:
    hash:
        usuario: defaultUser
        senha: defaultPassword
        chave: defaultKey

spring:
    data:
        mongodb:
            database: guiamedico_db
            
eureka:
    client:
        serviceUrl:
            defaultZone: http://10.142.0.110:8080/eureka/