server:
  port: 9001
spring:
  application:
    name: emed-security-server
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
  redis:
    uri: redis://localhost:6379
    repositories:
      enable: true
  datasource:
    url: jdbc:oracle:thin:@34.55.162.220/XE
    username: EMEDADM
    password: 3m3dAdm44ll01
    driver-class-name: oracle.jdbc.OracleDriver

swagger:
  title: Segurança
  description: Microserviço das APIs de Autorização

portalPaciente:
  #tempo em minutos
  tempoExpiracaoHashLogin: 15