spring:
  datasource:
    url: jdbc:oracle:thin:@(description=(address=(protocol=tcp)(host=172.20.1.209)(port=1521))(connect_data=(SERVER =DEDICATED)(service_name=emedprd_prd.subnetprdprivat.vcnemed.oraclevcn.com)))
    password: '3m3dRep44ll01$#Med' 
    hikari:
      maximum-pool-size: ${datasource.maximum-pool-size}
      minimum-idle: ${datasource.minimum-idle}

  kafka:
    bootstrap-servers: PLAINTEXT://localhost:9092