spring:
  datasource:
    maximum-pool-size: ${datasource.maximum-pool-size}
    minimum-idle: ${datasource.minimum-idle}
    url: jdbc:oracle:thin:@(description=(address=(protocol=tcp)(host=172.20.1.209)(port=1521))(connect_data=(SERVER =DEDICATED)(service_name=emedprd_prd.subnetprdprivat.vcnemed.oraclevcn.com)))
    password: 'EMdadm@!'
  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 2587
    username: AKIAVQV3IQRIVJLCYRNK
    password: BDCAWS3vMLmRjMoHAba1szirfjlJdG7X/huaX6bwkV+t
    properties:
      mail:
        smtp:
          from: mobile-dev@appunimed.com
      personal: Emed Temporário 
    personal: Emed4All

  kafka:
    bootstrap-servers: ${kafka.hosts}
