spring:
  data:
  datasource:
    url: jdbc:oracle:thin:@(description=(address=(protocol=tcp)(host=172.20.1.209)(port=1521))(connect_data=(SERVER =DEDICATED)(service_name=emedprd_prd.subnetprdprivat.vcnemed.oraclevcn.com)))
    password: 'EMdpep@!'
    hikari:
      maximum-pool-size: ${datasource.maximum-pool-size}
      minimum-idle: ${datasource.minimum-idle}
