spring:
  datasource:
    url: jdbc:oracle:thin:@(description=(address=(protocol=tcp)(host=172.20.1.209)(port=1521))(connect_data=(SERVER =DEDICATED)(service_name=emedprd_prd.subnetprdprivat.vcnemed.oraclevcn.com)))
    password: '3m3dRep44ll01$#Med'    
  #Kafka properties
  kafka:
    bootstrap-servers: PLAINTEXT://${kafka.host}:${kafka.port}
