server:
    port: ${PORT:${SERVER_PORT:9009}}
    
swagger:
    title: E-mail
    description: Microserviço das APIs de E-mail

spring:
    mail:
        properties:
            mail:
                smtp:
                    from: mobile@appunimed.com
            personal: App Unimed

logging: 
    level: 
        com.sun.mail.smtp: INFO