server:
  port: ${PORT:${SERVER_PORT:9001}}
  connection-timeout: 30000

authentication:
  oauth:
    clientidBeneficiario: umb
    secretBeneficiario: umb-secret-key
    tokenValidityInSeconds: 360
    refreshTokenValiditySeconds: 38000
    clientidCooperado: umb-cooperado
    secretCooperado: umb-secret-key-cooperado
    clientidWeb: umb-web
    secretWeb: umb-secret-key-web

swagger:
  title: Oauth
  description: Microserviço das APIs de Oauth

## Facebook ##
facebook:
  appId: 239657109785269
  appSecret: f5bb10741c6f79e00bbd9a2758cb6d1b

## GOOGLE ##
google:
  appId: 544497855649

# Login social apple
apple:
  clientId: br.coop.unimed.cliente.dev
  keyId: T7V7WX56JW
  teamId: 76QXR4SYHR
  certificate: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgvk0f0TpEo2tsWIm3jc1kWKmV10Bol4raH+wxjeMfkeegCgYIKoZIzj0DAQehRANCAASsAXR8XXi2XtZEHkoFaUQxwJZem0R6lwdcnrpT99z2dGJ6CBhYAV3sLY19XTzm53wL/irrAZXz6Ws29xKTbVK5
  pr:
    clientId: br.net.univision.dev.clientePR
    keyId: 4Y733LLC6H
    teamId: P29M7BQQGA
    certificate: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgE5BzYDj7pUvervZBUnSnA8ySrnLpA9XBXvAnIQA+8OOgCgYIKoZIzj0DAQehRANCAAR1lU4bd80Lf53d0Cqqla65C75OGyip+fyJ62gwPXp4pSt/Jwhbj301rkUDHaIf3sCQqrX+RQCPQXZhwrdsWx0v
  sp:
    clientId: br.net.univision.dev.clienteSP
    keyId: 4Y733LLC6H
    teamId: P29M7BQQGA
    certificate: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgE5BzYDj7pUvervZBUnSnA8ySrnLpA9XBXvAnIQA+8OOgCgYIKoZIzj0DAQehRANCAAR1lU4bd80Lf53d0Cqqla65C75OGyip+fyJ62gwPXp4pSt/Jwhbj301rkUDHaIf3sCQqrX+RQCPQXZhwrdsWx0v
  manaus:
    clientId: br.net.univision.dev.clienteManaus
    keyId: 4Y733LLC6H
    teamId: P29M7BQQGA
    certificate: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgE5BzYDj7pUvervZBUnSnA8ySrnLpA9XBXvAnIQA+8OOgCgYIKoZIzj0DAQehRANCAAR1lU4bd80Lf53d0Cqqla65C75OGyip+fyJ62gwPXp4pSt/Jwhbj301rkUDHaIf3sCQqrX+RQCPQXZhwrdsWx0v
  quer:
    clientId: br.com.appquer.dev
    keyId: QVA6W8UN48
    teamId: P29M7BQQGA
    certificate: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgxYNu+GCdW2ychUgHr79hX6JYme9bvMJLKAInCQXGfr6gCgYIKoZIzj0DAQehRANCAAQi+84gUGVGnTc2zoqEuuTpGvPG0Q2nb1yoFH98/M08XBiVYrp1RLU9MMoZqPCcAKfZIew2TTyguxkRK7Wa4Op+

## MESSAGES
field:
  registroCooperadoDto:
    codigo: Código do cooperado
    codigoSingular: Código da Unimed
    codigoConselho: Código do conselho
    ufConselho: UF do conselho
    dataNascimento: Data de nascimento
    cpf: CPF
  erroFrontDto:
    app: Aplicativo
    errorCode: Código do erro HTTP

spring:
  jpa:
    show_sql: false
