server:
    port: ${PORT:${SERVER_PORT:9050}}

swagger:
    title: App Quer / FitBit
    description: Microserviço das APIs de integração do App Quer com a FitBit

spring:
    jackson:
        serialization:
            write-dates-as-timestamps: false
        date-format: yyyy-MM-dd'T'HH:mm:ssZ
    data:
        mongodb:
            database: appquer-dev

