server:
  port: ${PORT:${SERVER_PORT:9036}}

swagger:
  title: tCuida Scheduler Services
  description: Microserviço das APIs da Plataforma tCuida
  contact:
    name: Univision
    url: ""
    email: ""

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
  data:
    mongodb:
      database: tcuida-dev
