spring:
    data:
        mongodb:
            uri: mongodb://root:Un1m3dM0b!l3@104.198.166.118/?authSource=admin&authMechanism=SCRAM-SHA-1
            database: vendas-dev
    datasource:
        url: jdbc:mysql://localhost:3307/uvo_venda_online_hom
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: unimedmobile
        password: unimedmobile
    jackson:
        serialization:
            write-dates-as-timestamps: false
dominio:
    externo:
        url:
            venda: http://localhost:8443/venda
            sgp-front: http://localhost:4201
            venda-contratacao: http://localhost:4200
            venda-adm: http://localhost:8087
uvo:
    ambiente: DEV
    path:
        vendaOnline: D:\venda-online
        contrato-plano: D:\venda-online\planos\contratos
        logo-plano: D:\venda-online\planos\logo
        logo-empresa: D:\venda-online\empresas\logo
        entidade-classe: D:\venda-online\entidade-classe
        documentoComprobatorio: D:\venda-online\imagens\documentoComprobatorio
        documentoComprobatorioArquivo: D:\venda-online\imagens\documentoComprobatorioArquivo
        guia-usuario: D:\venda-online\documentos\guia-usuario
        contrato: D:\venda-online\documentos\contrato
        templates: D:\venda-online\templates
        documentos-auxiliares: D:\venda-online\documentos\documentos-auxiliares
        historico-crm: D:\venda-online\CRM\historicos
        historico-crm-etapa: D:\venda-online\CRM\Etapas\historicos
        regulamentos: D:\venda-online\empresas\%s\produtos\%s\regulamentos
        cpt: D:\venda-online\empresas\%s\tipoVenda\%s\cpt
    password:
        regex: (?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}