spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306,127.0.0.1:3307/uvo_venda_online_hom
        driver-class-name: com.mysql.jdbc.Driver
        username: unimedmobile
        password: unimedmobile
    data:
        mongodb:
            database: vendas-hom

dominio:
    externo:
        url:
            venda: https://gateway-hom-lb.appunimed.com/venda
            sgp-front: https://sgp-hom.querounimed.com.br
            venda-contratacao: https://hom.querounimed.com.br
            venda-adm: https://adm-hom.querounimed.com.br

uvo:
    ambiente: HOM
    path:
        vendaOnline: /opt/apps/storage/upload/venda-online
        contrato-plano: /opt/apps/storage/upload/venda-online/planos/contratos
        logo-plano: /opt/apps/storage/upload/venda-online/planos/logo
        logo-empresa: /opt/apps/storage/upload/venda-online/empresas/logo
        entidade-classe: /opt/apps/storage/upload/venda-online/entidade-classe
        documentoComprobatorio: /opt/apps/storage/upload/venda-online/imagens/documentoComprobatorio
        documentoComprobatorioArquivo: /opt/apps/storage/upload/venda-online/imagens/documentoComprobatorioArquivo
        guia-usuario: /opt/apps/storage/upload/venda-online/guia-usuario
        contrato: /opt/apps/storage/upload/venda-online/documentos/contrato
        templates: /opt/apps/storage/upload/venda-online/templates
        documentos-auxiliares: /opt/apps/storage/upload/venda-online/documentos/documentos-auxiliares
        regulamentos: /opt/apps/storage/upload/venda-online/empresas/%s/produtos/%s/regulamentos
        historico-crm: /opt/apps/storage/upload/venda-online/CRM/historicos
        historico-crm-etapa: /opt/apps/storage/upload/venda-online/CRM/etapas/historicos
        cpt: /opt/apps/storage/upload/venda-online/empresas/%s/tipoVenda/%s/cpt
    mail:
        from: homologacao@querounimed.com.br
    password:
        regex: (?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}