server:
    port: ${PORT:${SERVER_PORT:9020}}
    
swagger:
    title: Vendas Online
    description: Microserviço das APIs de Vendas Online
    version: "@project.version@"
    termsOfServiceUrl: https://www.apache.org/licenses/LICENSE-2.0
    contact:
        name: Unimed Curitiba
        url: ""
        email: ""
    license: Apache License 2.0  
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0

security:
  basic:
    enabled: false
management:
  security:
    enabled: false

spring:
    datasource:
        url: jdbc:mysql://localhost:3309/uvo_venda_online
        driver-class-name: com.mysql.jdbc.Driver
        username: unimedmobile
        password: unimedmobile
    jackson:
        serialization:
            write-dates-as-timestamps: false
dominio:
    externo:
        url:
            venda: https://gateway-test.appunimed.com:8443/venda
            sgp-front: https://sgp-test.appunimed.com
            venda-contratacao: https://vendas-test.appunimed.com
            venda-adm: https://uvo-adm-test.appunimed.com
            cobertura-procedimento-garantido: http://www.ans.gov.br/planos-de-saude-e-operadoras/espaco-do-consumidor
uvo:
    ambiente: DEV
    path:
        vendaOnline: C:\DEV\venda-online
        contrato-plano: C:\DEV\venda-online\planos\contratos
        logo-plano: C:\DEV\venda-online\planos\logo
        logo-empresa: C:\DEV\venda-online\empresas\logo
        entidade-classe: C:\DEV\venda-online\entidade-classe
        documentoComprobatorio: C:\DEV\venda-online\imagens\documentoComprobatorio
        documentoComprobatorioArquivo: C:\DEV\venda-online\imagens\documentoComprobatorioArquivo
        guia-usuario: C:\DEV\venda-online\documentos\guia-usuario
        contrato: C:\DEV\venda-online\documentos\contrato
        templates: C:\DEV\venda-online\templates
        documentos-auxiliares: C:\DEV\venda-online\documentos\documentos-auxiliares
        historico-crm: C:\DEV\venda-online\CRM\historicos
        historico-crm-etapa: C:\DEV\venda-online\CRM\Etapas\historicos
        regulamentos: C:\DEV\venda-online\empresas\%s\produtos\%s\regulamentos
        cpt: C:\DEV\venda-online\empresas\%s\tipoVenda\%s\cpt
    mail:
        from: mobile-dev@appunimed.com
    password:
        regex: ^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d$%@!*#_;:.]{8,}$
    url:
        ans: http://www.ans.gov.br/planos-de-saude-e-operadoras/contratacao-e-troca-de-plano/guia-ans-de-planos-de-saude
    config:
        quantidadeDiasExportar: 180
    lgpd:
        conteudo: Olá <REQUISITANTE>,<br /><br />Agradecemos pelo contato com a Univision em <DATA_CONTATO>. Ressaltamos que sua privacidade é importante para nós.<br />Concluímos o processamento da sua solicitação, nos termos da Lei Federal n° 13709/2018, a Lei Geral de Proteção de Dados (LGPD).<br />Usamos seus dados para melhorar a sua experiência no uso dos nossos produtos e serviços. Agradecemos profundamente sua contribuição individual pois os dados que coletamos e analisamos contribuem para nossa visão de criar um mundo onde o cuidado com a saúde esteja nas mãos de todas as pessoas.<br />Atenciosamente.<br />Univision - Tecnologia em saúde.
        rodape: 
pagamento:
    boleto:
        itau:
            ambiente: 2