spring:
    datasource:
        url: jdbc:mysql://localhost:3306,localhost:3307/uvo_venda_online
        driver-class-name: com.mysql.jdbc.Driver
        username: unimedmobile
        password: unimedmobile
    data:
        mongodb:
            database: vendas

eureka:
    client:
        serviceUrl:
            defaultZone: http://10.142.0.110:8080/eureka/

dominio:
    externo:
        url:
            venda: https://gateway.querounimed.com.br/venda
            sgp-front: https://sgp.querounimed.com.br
            venda-contratacao: https://querounimed.com.br
            venda-adm: https://adm.querounimed.com.br

uvo:
    ambiente: PROD
    path:
        vendaOnline: /opt/apps/storage/upload/venda-online
        contrato-plano: /opt/apps/storage/upload/venda-online/planos/contratos
        logo-plano: /opt/apps/storage/upload/venda-online/planos/logo
        logo-empresa: /opt/apps/storage/upload/venda-online/empresas/logo
        entidade-classe: /opt/apps/storage/upload/venda-online/entidade-classe
        documentoComprobatorio: /opt/apps/storage/upload/venda-online/imagens/documentoComprobatorio
        documentoComprobatorioArquivo: /opt/apps/storage/upload/venda-online/imagens/documentoComprobatorioArquivo
        guia-usuario: /opt/apps/storage/upload/venda-online/guia-usuario
        contrato: /opt/apps/storage/upload/venda-online/documentos/contrato
        templates: /opt/apps/storage/upload/venda-online/templates
        documentos-auxiliares: /opt/apps/storage/upload/venda-online/documentos/documentos-auxiliares
        regulamentos: /opt/apps/storage/upload/venda-online/empresas/%s/produtos/%s/regulamentos
        historico-crm: /opt/apps/storage/upload/venda-online/CRM/historicos
        historico-crm-etapa: /opt/apps/storage/upload/venda-online/CRM/etapas/historicos
        cpt: /opt/apps/storage/upload/venda-online/empresas/%s/tipoVenda/%s/cpt
    mail:
        from: naoresponder@querounimed.com.br